#!/bin/bash
set -e # Exit on error

app=mattermost

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
sudo mkdir -p $backup_dir

# Backup sources
echo "Backup sources from /var/www/$app…"
sudo cp -a /var/www/$app/. $backup_dir/sources

# Backup database
echo "Backup database…"
root_pwd=$(sudo cat /etc/yunohost/mysql)
sudo sh -c "mysqldump -u root -p$root_pwd mattermost > $backup_dir/mattermost.sql"

# Backup uploaded files
echo "Backup uploaded files…"
sudo cp -a /home/yunohost.app/mattermost/. $backup_dir/data

# Copy Nginx and YunoHost parameters to make the script "standalone"
echo "Backup Yunohost configuration…"
sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
domain=$(sudo yunohost app setting $app domain)
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
