#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action=stop --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# EDIT MATTERMOST CONFIG
#=================================================
ynh_script_progression "Updating configuration..."

# Main config File
ynh_replace --match="\"SiteURL\": \".*\""  --replace="\"SiteURL\": \"https://${new_domain}${new_path}\"" --file="$install_dir/config/config.json"
ynh_replace --match="\"FeedbackEmail\": \".*\"" --replace="\"FeedbackEmail\": \"no-reply@${new_domain}\"" --file="$install_dir/config/config.json"

ynh_store_file_checksum "$install_dir/config/config.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
