#!/bin/bash
set -u  # treat unset variables as an error

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get mattermost domain)
db_name="mattermost"
db_user="mmuser"
final_path="/var/www/$app"
data_path="/home/yunohost.app/$app"
logs_path="/var/log/$app"

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# Remove systemd service
if $(sudo systemctl -q is-active "$app"); then
  sudo systemctl stop "$app"
fi
ynh_remove_systemd_config

# Legacy, for older versions of this app which used supervisor
if [ -f "/etc/supervisor/conf.d/${app}.conf" ]; then
  sudo supervisorctl stop "$app"
  sudo rm -f "/etc/supervisor/conf.d/${app}.conf"
fi

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

if sudo yunohost service status | grep -q "$app"; then
  sudo yunohost service remove "$app"
fi

#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================

ynh_mysql_remove_db "$db_user" "$db_name"

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "$final_path"
ynh_secure_remove "$data_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_remove_nginx_config

#=================================================
# REMOVE LOG FILE
#=================================================

sudo rm -rf "$logs_path"

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete "$app"
