#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R $app:www-data "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE THE DATABASE
#=================================================
ynh_script_progression "Restoring the database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

logs_path="/var/log/$app"
mkdir -p $logs_path
chown -R $app: $logs_path

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Collaboration platform built for developers" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=$app --action=start --log_path=systemd #--wait_until="Started mattermost"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
